// PENGULANGAN - REPETITION

/*
    DALAM PEMOGRAMAN,PENGULANGAN MERUPAKAN PROSES MELAKUKAN  PERINTAH YANHG SAMA SECARA SAMPAI BATAS TERTENTU YANG DITENTUKAN.
    PENGULANGAN DINYATAKAN KE DALAM BLOK PROGRAM, YANG DAPAT  DIBUAT  MENGGUNAKAN PERINTAH  WHILE, DO-WHILE, DAN FOR.
    SELAIN KETIGA PERINTAH TERSEBUT, JAVASCRIPT  JUGA  MENYEDIAKAN PERINTAH  FOR-IN DAN FOR-OF UNTUK MELAKUKAN PROSES 
    PENELUSURAN  INDEKS MAUPUN  ELEMENT DIDALAM SUATU OBJEK KOLEKSI (MISALNYA ARRAY ) .

    PROSES PENELURUSAN ELEMENT DIDALAM KOLEKSI  SERIMG DIKAITKAN  DENGAN MATERI TENTANG PENGULANGAN .

    SAMA SEPERTI BLOK PEMILIHAN, BLOK PENGULANGAN JUGA MEMILIKI KONDISI YANG PERLU DI PERIKSA .
    PROSES PENGULANGAN AKAN TERUS DILAKUKAN SELAMA KONDISI BERNILAI TRUE.
*/